/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 阅读
  reading: [{type: 'autogenerated', dirName: 'reading'}],

  // 计算机基础
  basics: [{type: 'autogenerated', dirName: 'computer-basics/basics'}],
  algorithm: [{type: 'autogenerated', dirName: 'computer-basics/algorithm'}],
  'dev-efficiency': [{type: 'autogenerated', dirName: 'computer-basics/dev-efficiency'}],
  server: [{type: 'autogenerated', dirName: 'computer-basics/server'}],

  // 前端
  javascript: [{type: 'autogenerated', dirName: 'frontend/javascript'}],
  react: [{type: 'autogenerated', dirName: 'frontend/react'}],
  vue: [{type: 'autogenerated', dirName: 'frontend/vue'}],
  deploy: [{type: 'autogenerated', dirName: 'frontend/deploy'}],

  // 后端
  java: [{type: 'autogenerated', dirName: 'backend/java'}]
};

module.exports = sidebars;
